import 'package:shop_ke/core/models/firestore_models/store.dart';

const List<String> countyList = [
  Store.defaultCounty, //Directive to choose a county
  'Baringo County',
  'Bomet County',
  'Bungoma County',
  'Busia County',
  'Elgeyo-Marakwet County',
  'Embu County',
  'Garissa County',
  'Homa-bay County',
  'Isiolo County',
  'Kajiado County',
  'Kakamega County',
  'Kericho County',
  'Kiambu County',
  'Kilifi County',
  'Kirinyaga County',
  'Kisii County',
  'Kisumu County',
  'Kitui County',
  'Kwale County',
  'Laikipia County',
  'Lamu County',
  'Machakos County',
  'Makueni County',
  'Mandera County',
  'Marsabit County',
  'Meru County',
  'Migori County',
  'Mombasa County',
  'Muranga County',
  'Nairobi County',
  'Nakuru County',
  'Nandi County',
  'Narok County',
  'Nyamira County',
  'Nyandarua County',
  'Nyeri County',
  'Samburu County',
  'Siaya County',
  'Taita-Taveta County',
  'Tana River County',
  'Tharaka-Nithi County',
  'Trans-Nzoia County',
  'Turkana County',
  'Uasin Gishu County',
  'Vihiga County',
  'Wajir County',
  'West Pokot County',
];

const Map<String, String> countiesMap = {
  'BARINGO': 'Baringo County',
  'BOMET': 'Bomet County',
  'BUNGOMA': 'Bungoma County',
  'BUSIA': 'Busia County',
  'ELGEYO-MARAKWET': 'Elgeyo-Marakwet County',
  'EMBU': 'Embu County',
  'GARISSA': 'Garissa County',
  'HOMA-BAY': 'Homa-bay County',
  'ISIOLO': 'Isiolo County',
  'KAJIADO': 'Kajiado County',
  'KAKAMEGA': 'Kakamega County',
  'KERICHO': 'Kericho County',
  'KIAMBU': 'Kiambu County',
  'KILIFI': 'Kilifi County',
  'KIRINYAGA': 'Kirinyaga County',
  'KISII': 'Kisii County',
  'KISUMU': 'Kisumu County',
  'KITUI': 'Kitui County',
  'KWALE': 'Kwale County',
  'LAIKIPIA': 'Laikipia County',
  'LAMU': 'Lamu County',
  'MACHAKOS': 'Machakos County',
  'MAKUENI': 'Makueni County',
  'MANDERA': 'Mandera County',
  'MARSABIT': 'Marsabit County',
  'MERU': 'Meru County',
  'MIGORI': 'Migori County',
  'MOMBASA': 'Mombasa County',
  'MURANGA': 'Muranga County',
  'NAIROBI': 'Nairobi County',
  'NAKURU': 'Nakuru County',
  'NANDI': 'Nandi County',
  'NAROK': 'Narok County',
  'NYAMIRA': 'Nyamira County',
  'NYANDARUA': 'Nyandarua County',
  'NYERI': 'Nyeri County',
  'SAMBURU': 'Samburu County',
  'SIAYA': 'Siaya County',
  'TAITA-TAVETA': 'Taita-Taveta County',
  'TANA RIVER': 'Tana River County',
  'THARAKA-NITHI': 'Tharaka-Nithi County',
  'TRANS-NZOIA': 'Trans-Nzoia County',
  'TURKANA': 'Turkana County',
  'UASIN GISHU': 'Uasin Gishu County',
  'VIHIGA': 'Vihiga County',
  'WAJIR': 'Wajir County',
  'WEST POKOT': 'West Pokot County',
};
