import 'package:flutter/material.dart';

class Order {
  String orderId;
  String userId;
  String orderStatus;
  String createdAt;
  double _orderTotal;

  static const String Pending = "Pending";
  static const String Cancelled = "Cancelled";
  static const String Complete = "Complete";

  Order({
    this.orderId, //Autogenerated in the backend
    this.createdAt, //Set in the database
    this.orderStatus = Pending, //Has default value when placing order
    @required this.userId,
  });

  Order.fromMap(Map<String, dynamic> map) {
    orderId = map['orderId'];
    userId = map['userId'];
    createdAt = map['orderTimestamp'];
    orderStatus = map['orderStatus'];
    orderTotal = map['orderTotal'];
  }

  Map<String, dynamic> toMap() {
    return {
      'userId': userId,
      'createdAt': createdAt,
      'orderStatus': orderStatus,
      'orderTotal': orderTotal,
    };
  }

  set orderTotal(var value) {
    switch (value.runtimeType) {
      case int:
        int orderTotal = value;
        _orderTotal = orderTotal.toDouble();
        break;

      case double:
        _orderTotal = value;
        break;

      default:
        throw new Exception('Order total is a ${value.runtimeType} not double or int');
        break;
    }

    return value;
  }

  double get orderTotal => _orderTotal;
}
