import 'package:flutter/material.dart';

class Order {
  String id;
  final String userId;
  final String orderStatus;
  final String createdAt;
  final double orderTotal;

  static const String Pending = "Pending";
  static const String Cancelled = "Cancelled";
  static const String Complete = "Complete";

  Order({
    this.id, //Autogenerated in the backend
    this.createdAt, //Set in the database
    this.orderStatus = Pending, //Has default value when placing order
    @required this.userId,
    @required this.orderTotal,
  });

  factory Order.fromMap(Map<String, dynamic> map) {
    return Order(
      id: map['id'],
      userId: map['userId'],
      createdAt: map['orderTimestamp'],
      orderStatus: map['orderStatus'],
      orderTotal: map['orderTotal'],
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'userId': userId,
      'createdAt': createdAt,
      'orderStatus': orderStatus,
      'orderTotal': orderTotal
    };
  }
}
